### ISSUE TITLE
Support for generic classes

### ISSUE THREAD

**Issue by jepperaskdk** [lukemansell/dotnet-auto-dependency-registration#13]
Hey,

I'm playing around some more with this package, and found this. Registration seems to fail for generic classes, e.g. this:

```
using AutoDependencyRegistration.Attributes;

namespace WebApplication1
{
    [RegisterClassAsTransient]
    public class Generic<T> : IGeneric<T>
    {
    }
}
```

```
System.InvalidOperationException: Unable to resolve service for type 'WebApplication1.IGeneric`1[WebApplication1.WeatherForecast]' while attempting to activate 'WebApplication1.Controllers.WeatherForecastController'.
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.GetService(IServiceProvider sp, Type type, Type requiredBy, Boolean isDefaultParameterRequired)
   at lambda_method3(Closure , IServiceProvider , Object[] )
   at Microsoft.AspNetCore.Mvc.Controllers.ControllerActivatorProvider.<>c__DisplayClass7_0.<CreateActivator>b__0(ControllerContext controllerContext)
   at Microsoft.AspNetCore.Mvc.Controllers.ControllerFactoryProvider.<>c__DisplayClass6_0.<CreateControllerFactory>g__CreateController|0(ControllerContext controllerContext)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
```

I found this way of registering a generic class, which is the workaround - but it would be nice if the library would register it as well:
```
builder.Services.AddScoped(typeof(IGeneric<>), typeof(Generic<>));
```
https://stackoverflow.com/a/56273589/3717691

**Comment by lukemansell** [comment]
Thanks for the issue @jepperaskdk - I'll take a look as it's supposed to work. We have a project that is using it fine with:

```
[RegisterClassAsSingleton]
    public class CacheService<T> : ICacheService<T>
    {
```

for example. I'll see if I can work out what is going on for your example.

**Comment by jepperaskdk** [comment]
Let me know if you want me to push a repository with the failing setup.. Maybe I'm doing something incorrectly as well.

**Comment by lukemansell** [comment]
@jepperaskdk - if you want to push a repo you were trying this with I can double check against what you were trying to test with too. I've managed to get this working locally for a solution
