### ISSUE TITLE
System.InvalidOperationException: Unable to resolve service

### ISSUE THREAD

**Issue by DevD4v3** [lukemansell/dotnet-auto-dependency-registration#8]
I have used this library in [this project](https://github.com/MrDave1999/test-auto-dependency-registration) and I don't know why it doesn't work. I get the following exception:
```sh
System.InvalidOperationException: Unable to resolve service for type 'WebApiExample.Features.Contabilidad.Pucs.PucService' while attempting to activate 'WebApiExample.Controllers.WeatherForecastController'.
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.GetService(IServiceProvider sp, Type type, Type requiredBy, Boolean isDefaultParameterRequired)
   at lambda_method3(Closure, IServiceProvider, Object[])
   at Microsoft.AspNetCore.Mvc.Controllers.ControllerFactoryProvider.<>c__DisplayClass6_0.<CreateControllerFactory>g__CreateController|0(ControllerContext controllerContext)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)
```
I have tried to follow the steps in the documentation and nothing.

In `Program.cs` I call:
```cs
builder.Services.AutoRegisterDependencies();
```
See https://github.com/MrDave1999/test-auto-dependency-registration/blob/master/Program.cs#L11.

And here I have the test classes:
```cs
[RegisterClassAsScoped]
public class PucService
{
    public PucService(PucDao dao)
    {
        
    }
}

[RegisterClassAsScoped]
public class PucDao
{
    public PucDao() { }
}
```
See https://github.com/MrDave1999/test-auto-dependency-registration/blob/master/Features/Contabilidad/Pucs/PucService.cs#L3-L18.

And finally, I use the class of service in the controller:
```cs
public class WeatherForecastController : ControllerBase
{
    public WeatherForecastController(
        PucService service,
        ILogger<WeatherForecastController> logger)
    {
        _logger = logger;
        _service = service;
    }
}
```
See https://github.com/MrDave1999/test-auto-dependency-registration/blob/master/Controllers/WeatherForecastController.cs#L18-L24.

**Technical details (context):**
- .NET 7.0.3
- Linux Mint 20 Cinnamon
- AutoDependencyRegistration v3.0.0

**Comment by lukemansell** [comment]
Thanks for the issue.

I'll take a look at this soon and take a look at what is going on

**Comment by lukemansell** [comment]
Hey @MrDave1999 - thanks for reporting this issue. This was an unintended side effect of some changes I made in the latest release. I've fixed it up and ensured it works on your solution and with the unit tests in the solution.

You should be able to upgrade to 3.1.0 which will fix this in the next 30 minutes.

**Comment by DevD4v3** [comment]
@lukemansell Thanks for the new release. I just tested it and it works.
